- poetry.lock
- pyproject.toml
- src/govee_ble/__init__.py
- src/govee_ble/parser.py
BREAKING CHANGE: bump sensor-state-data to 2
> feat: refactor for sensor-state-data 2

- src/govee_ble/parser.py
- tests/test_parser.py
Fixes https://github.com/home-assistant/core/issues/76352
> fix: add 818 to the manufacturer_ids for the gvh5185

- .flake8
- src/govee_ble/parser.py
- tests/test_parser.py
See https://github.com/home-assistant/core/issues/77563
> feat: add support for additional H5185 firmware

- src/govee_ble/parser.py
- tests/test_parser.py
https://github.com/home-assistant/core/issues/79029
> feat: add support for another H5181 variant

- src/govee_ble/parser.py
- tests/test_parser.py
> feat: add support for yet another H5183 variant

- src/govee_ble/parser.py
- tests/test_parser.py
Also matches on service_uuids as well now to reduce the number of lib updates we will need in the future
> fix: handle another H5181

- src/govee_ble/parser.py
- tests/test_parser.py
Reverts Bluetooth-Devices/govee-ble#49
fixes #48
> fix: reject impossible temp values take 2

- src/govee_ble/parser.py
- tests/test_parser.py
The humidity part is kept in the temperature part.
Round temp_as_float to remove humidity part.
> fix: round temp values

- src/govee_ble/parser.py
- tests/test_parser.py
Ignore temperature and humidity when error bit is set
Fixes https://github.com/Bluetooth-Devices/govee-ble/issues/51
> feat: implement error bit

- src/govee_ble/parser.py
- tests/test_parser.py
- Feat: Add Govee H5198
- Fix: Govee H5051 in little endian #56
> feat: add govee h5198

- src/govee_ble/parser.py
- tests/test_parser.py
H5198 also sends a low temperature alarm for each probe
> feat: add low temperature alarm to h5198

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- poetry.lock
> fix: update isort to fix ci

- src/govee_ble/parser.py
- tests/test_parser.py
Implements and closes https://github.com/Bluetooth-Devices/govee-ble/issues/46
> feat: add support for govee h5055

- src/govee_ble/parser.py
- tests/test_parser.py
> feat: add support for H5108

- src/govee_ble/parser.py
- tests/test_parser.py
> feat: add support for H5106

- src/govee_ble/parser.py
- tests/test_parser.py
It looks like the newer 5179s use the same format as the H5101/H5102/H5104/H5108/H5174/H5177 models
> feat: add support for newer 5179 firmware

- src/govee_ble/parser.py
Fixes https://github.com/home-assistant/core/issues/139374
> fix: change minimum temp to -40

- src/govee_ble/parser.py
- tests/test_parser.py
> feat: add support for H5110

- tests/test_parser.py
https://github.com/home-assistant/core/issues/142305#issuecomment-2911223694
> chore: add more coverage for GVH5110

- src/govee_ble/parser.py
- tests/test_parser.py
Add support for Govee H5191
Reordered the tests in numercal order
> feat: add support for H5191
